### ISSUE TITLE
Reload the image

### ISSUE THREAD

**Issue by dabasmoti** [psmathur/keras-vision-app#5]
Hi,
Thanks for the repository
I am using the app for object detection with tensorflow
after drawing the bbox , i want to reload the chosen img for display the bbox
can you please help me with that?
Thanks

**Comment by psmathur** [comment]
sorry for the super delayed 1-year late reply, you can check out this article for creating a rectangle on top of you prediction region => https://www.pyimagesearch.com/2020/06/22/turning-any-cnn-image-classifier-into-an-object-detector-with-keras-tensorflow-and-opencv/
